name: Deploy to Somee via FTP

on:
  push:
    branches:
      - main   # chạy khi push nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Upload file lên Somee bằng FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PW }}
          local-dir: ./                         # thư mục gốc repo
          server-dir: /www.ossdeploy27112025.somee.com/  # thư mục trên hosting
          protocol: ftp                        # dùng FTP (không phải SFTP)
